### ISSUE TITLE
Paper1.21.1環境でプラグインを導入して、↓のようなエラーになってしまします

### ISSUE THREAD

**Issue by kakun-777** [okocraft/Box#386]
[14:48:22 INFO]: .kakun_xbox9651 issued server command: /box
[14:48:26 ERROR]: Could not pass event InventoryClickEvent to Box v6.0.0-rc.1
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at Box-6.0.0-rc.1.jar/net.okocraft.box.feature.gui.internal.listener.InventoryListener.onClick(InventoryListener.java:31) ~[Box-6.0.0-rc.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor120.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3212) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:48:26 ERROR]: Could not pass event InventoryClickEvent to Box v6.0.0-rc.1
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at Box-6.0.0-rc.1.jar/net.okocraft.box.feature.gui.internal.listener.InventoryListener.onClick(InventoryListener.java:31) ~[Box-6.0.0-rc.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor120.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3212) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by kakun-777** [comment]
Geminiに聞いてみたら
エラー解析 (Japanese Error Analysis)
このエラーログは、Minecraftサーバー上で発生した互換性問題を示しています。

問題:

プラグイン "Box" (バージョン 6.0.0-rc.1) は、org.bukkit.inventory.InventoryView クラスをクラスとして扱おうとしています。
Minecraft 1.21 以降では、このクラスはインターフェースに変更されました。
エラー内容の詳細:

プレイヤーが /box コマンドを実行します。(14:48:22 INFO)
"Box" プラグインの InventoryListener.onClick メソッドの 31行目でエラーが発生します。(14:48:26 ERROR)
このメソッドは、InventoryView をクラスとして使用しようとしますが、現在はインターフェースであるため、エラーになります。
スタックトレースの説明:

スタックトレースは、エラーが発生したコード実行の順序を示しています。
プレイヤーによるコマンド実行から、"Box" プラグインのコードでのエラー発生までを示しています。
解決方法:

"Box" プラグインの更新 (推奨):
"Box" プラグインのドキュメントや GitHub リポジトリを確認し、Minecraft 1.21 以降に対応した更新がないか調べてください。最新バージョンが利用できる場合は、更新することで解決します。これが最も確実な解決方法です。
Minecraft サーバーのダウングレード (推奨されません):
この方法は、セキュリティ上の脆弱性や他のプラグインとの互換性問題を引き起こす可能性があるため、あまり推奨されません。どうしても解決できない場合は、Minecraft 1.20.6 以前へのダウングレードも検討できますが、セキュリティリスクを伴うので注意が必要です。
補足:

"Box" プラグインの開発者に連絡し、互換性問題について報告することを検討してください。開発者が問題を認識することで、今後のバージョンの更新につながります。
類似した機能を持つ Minecraft 1.21 以降に対応した別のプラグインを探すことも検討できます。
と言われました

**Comment by Siroshun09** [comment]
リリースにあるバージョンでは1.21.1に対応していません。ソースコードからコンパイルすることで使用できます。
https://github.com/okocraft/Box?tab=readme-ov-file#compiling-from-source
